### ISSUE TITLE
Mysqloo booleans stored as tinyint(1) but Where(boolean) does not convert bool to number

### ISSUE THREAD

**Issue by ottworks** [alexgrist/GLua-MySQL-Wrapper#4]
SQLite uses true/false but mysqloo uses 1/0. The wrapper fails to translate.

**Comment by alexgrist** [comment]
Moan at Rubat or Kilburn or validate your results using tobool, not a major issue since you should be validating types anyway.

**Comment by ottworks** [comment]
No, you're wrong. When I store true, I expect Where(true) to find that
result. I can't fix this without modifying the wrapper, in which case
you've failed.

**Comment by alexgrist** [comment]
Failed? It's a simple and easy to use SQL wrapper which makes writing queries for each different module an easy task, if you can't check your result types because SQLite returns a boolean value differently then that's a failure on your part not mine.

**Comment by SpencerSharkey** [comment]
I prefer the wrapper to persist the value types returned by the original modules... makes more sense.

**Comment by SpencerSharkey** [comment]
MySQL doesn't even store Boolean values, how do you expect a "where" clause to find a type that MySQL doesn't even know about. How has he failed? I'm dying to know.

**Comment by ottworks** [comment]
Because SQLite does. MySQL stores it as aptinyint(1), however the wrapper doesn't let you know that and just silently converts it. Am I correct that a wrapper is supposed to provide a generic frontend that behaves consistently?

**Comment by SpencerSharkey** [comment]
Well what happens if you want to store and retrieve an aptinyint that isn't true and false? Think of all the use cases. It's silly enough you're trying to stuff a boolean value into a MySQL table. Don't use bools if some of the modules you want to support don't support them.

**Comment by ottworks** [comment]
Am I correct that a wrapper is supposed to provide a generic frontend that behaves consistently?

**Comment by SpencerSharkey** [comment]
No, not at the expense of breaking other things for your feature request.
